export const dummyNasabah = [
  {
    id: 1,
    name: "Muhammad Naufan Arifin Sihombing",
    phone: "0812481241",
    email: "mr.naufan67@gmail.com",
    status: "Contacted",
  },
  {
    id: 2,
    name: "Sarah Lim",
    phone: "0812123456",
    email: "sarah.lim@example.com",
    status: "Pending",
  },
  {
    id: 3,
    name: "Ahmad Yusuf",
    phone: "0813345678",
    email: "ahmad.yusuf@example.com",
    status: "Not Contacted",
  },
  {
    id: 4,
    name: "Jessica Tan",
    phone: "0812987456",
    email: "jess.tan@example.com",
    status: "Contacted",
  },
  {
    id: 5,
    name: "David Setiawan",
    phone: "0813777888",
    email: "david.setiawan@example.com",
    status: "Closed",
  },
  {
    id: 6,
    name: "Rina Anggraini",
    phone: "0812456321",
    email: "rina.anggraini@example.com",
    status: "Pending",
  },
  {
    id: 7,
    name: "Hendra Pratama",
    phone: "0812334455",
    email: "hendra.pratama@example.com",
    status: "Contacted",
  },
  {
    id: 8,
    name: "Maya Kartika",
    phone: "0812556777",
    email: "maya.kartika@example.com",
    status: "Not Contacted",
  },
  {
    id: 9,
    name: "Andi Saputra",
    phone: "0812667890",
    email: "andi.saputra@example.com",
    status: "Closed",
  },
  {
    id: 10,
    name: "Lisa Wijaya",
    phone: "0812778999",
    email: "lisa.wijaya@example.com",
    status: "Contacted",
  },
    {
    id: 11,
    name: "Muhammad Naufan Arifin Sihombing",
    phone: "0812481241",
    email: "mr.naufan67@gmail.com",
    status: "Contacted",
  },
  {
    id: 12,
    name: "Sarah Lim",
    phone: "0812123456",
    email: "sarah.lim@example.com",
    status: "Pending",
  },
  {
    id: 13,
    name: "Ahmad Yusuf",
    phone: "0813345678",
    email: "ahmad.yusuf@example.com",
    status: "Not Contacted",
  },
  {
    id: 14,
    name: "Jessica Tan",
    phone: "0812987456",
    email: "jess.tan@example.com",
    status: "Contacted",
  },
  {
    id: 15,
    name: "David Setiawan",
    phone: "0813777888",
    email: "david.setiawan@example.com",
    status: "Closed",
  },
  {
    id: 16,
    name: "Rina Anggraini",
    phone: "0812456321",
    email: "rina.anggraini@example.com",
    status: "Pending",
  },
  {
    id: 17,
    name: "Hendra Pratama",
    phone: "0812334455",
    email: "hendra.pratama@example.com",
    status: "Contacted",
  },
  {
    id: 18,
    name: "Maya Kartika",
    phone: "0812556777",
    email: "maya.kartika@example.com",
    status: "Not Contacted",
  },
  {
    id: 19,
    name: "Andi Saputra",
    phone: "0812667890",
    email: "andi.saputra@example.com",
    status: "Closed",
  },
  {
    id: 20,
    name: "Lisa Wijaya",
    phone: "0812778999",
    email: "lisa.wijaya@example.com",
    status: "Contacted",
  },
];